sudo: required
dist: trusty

language: generic

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake blender python3.4-dev python3-numpy libgl1-mesa-dev libsdl1.2debian xvfb

script: "time ./.travis.bash"

notifications:
  irc: "irc.freenode.org#morse"
